### ISSUE TITLE
PORT MADNESSS

### ISSUE THREAD

**Issue by nAnjewierden** [buildInAmsterdam-cl/build-in-amsterdam-cl#14]
Some of are having issues using the port we specify, not a huge deal but annoying and perplexing. Lets figure out whats going on!

**Comment by jonbaxt** [comment]
The way I've found to get this solved is instead of declaring port in the .env, I've experimented with relabeling it to server_port. This seems to be an issue with maybe declaring port makes the program think that you are trying to go off of something else other than port 3000 for the main app even though it is the server port we are trying to declare. 

Also, make sure that the server_port number is 3003 since that is what is labeled as the proxy server for development. Doing these two may solve the problem.

**Comment by jonbaxt** [comment]
I think everyone is one the same page with this issue now. The port is hard coded for the time being and seems to not be giving problems now in the project.
